git:
  depth: 10

language: python

env:
  global:
     - COMMIT=${TRAVIS_COMMIT::8}

jobs:
  include:
    - stage: "Sanity Check"
      name: "PEP8 syntax check"
      script:
      - python -m pip install pycodestyle flake8
      - python -m pycodestyle challenge_w3
      - python -m flake8 challenge_w3
    - stage: "Test"
      name: "Build docker"
      script:
        - docker-compose build
        - docker-compose up &
        - bash test.sh
    - stage: "Test"
      name: "Create a plan for terraform"
      script:
        - ./bin/terraform init terraform
        - ./bin/terraform plan terraform
    - stage: "Publish"
      name: "Publish docker image"
      script:
        - pip install awscli
        - $(aws ecr get-login --no-include-email --region ap-northeast-1)
        - docker build -t web-app .
        - docker tag web-app:latest 691083515862.dkr.ecr.ap-northeast-1.amazonaws.com/web-app:${TRAVIS_BRANCH}.${COMMIT}
        - docker tag web-app:latest 691083515862.dkr.ecr.ap-northeast-1.amazonaws.com/web-app:${TRAVIS_BRANCH}
        - docker push 691083515862.dkr.ecr.ap-northeast-1.amazonaws.com/web-app:${TRAVIS_BRANCH}.${COMMIT}
        - docker tag web-app:latest 691083515862.dkr.ecr.ap-northeast-1.amazonaws.com/web-app:${TRAVIS_BRANCH}
    - stage: "Publish"
      name: "Apply changes on Terraform"
      script:
        - ./bin/terraform init terraform
        - ./bin/terraform apply -auto-approve terraform
      if: branch = master