git:
  depth: 10

language: python

jobs:
  include:
    - stage: "pep8"
      script:
      - python -m pip install pycodestyle flake8
      - python -m pycodestyle challenge_w3
      - python -m flake8 challenge_w3
    - stage: "build"
      script:
        - docker-compose build
        - docker-compose up &
        - bash test.sh
