version: "3.3"

services:
  w3-webapp:
    build: .
    networks:
      - default
    environment: 
      - REDIS_URL=w3-redis
    ports:
      - 5000:5000
    container_name: w3-webapp

  w3-redis:
    image: docker.io/library/redis:alpine
    networks:
      - default
    ports:
      - 6379:6379
    container_name: w3-redis


networks:
  default: